import Config

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Configure your database
config :radio_api, RadioApi.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "radio_api_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# ## SSL Support
# debugging and code reloading.
#
#
# In order to use HTTPS in development, a self-signed
# The watchers configuration can be used to run external
# certificate can be generated by running the following
# watchers to your application. For example, we can use it
# Mix task:
# to bundle .js and .css sources.
#
#     mix phx.gen.cert
config :radio_api, RadioApiWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  #
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # Run `mix help phx.gen.cert` for more information.
  #  http: [ip: {127, 0, 0, 1}, port: 4000],
  #
  # The `http:` config above can be replaced with:
  #
  #     https: [
  #       port: 4001,
  #       cipher_suite: :strong,
  #       keyfile: "priv/cert/selfsigned_key.pem",
  #       certfile: "priv/cert/selfsigned.pem"
  #     ],
  #
  # If desired, both `http:` and `https:` keys can be
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "HoPlFWd8cFjYqSWChA/tycobwY9EmEUxPjTIMPyQQZ+oxNJP5tdI5+3DIMU+MShN",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:radio_api, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:radio_api, ~w(--watch)]}
  ]

# Watch static and templates for browser reloading.
# configured to run both http and https servers on
# different ports.

config :radio_api, RadioApiWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/radio_api_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :radio_api, dev_routes: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
